GET http://localhost:5000

###

GET http://localhost:5000/view

###

GET http://localhost:5000/crisis

###Create Team

POST http://localhost:5000/create
content-type: application/json

{
  "teamName": "Marauders",
  "password": "12345678",
  "leader": {
    "name": "Aryan",
    "phone": "8146740057",
    "year": "3rd",
    "branch": "ENC",
    "email": "aryan2563737@gmail.com"
  }
}


###Login

POST http://localhost:5000/
content-type: application/json

{
  "teamName": "Marauders",
  "password":"11223344"  
}


###Join

POST http://localhost:5000/join
content-type: application/json

{
  "code":"seDnuIAL3",
  "member": {
    "name": "random",
    "phone": "1234567893",
    "year": "3rd",
    "branch": "ENC",
    "email": "test4@test.com"
  }
}

###Forgot Password
POST http://localhost:5000/forgot-password
content-type: application/json

{
  "email":"aryan2563737@gmail.com"
}


###Buy Bombs

POST http://localhost:5000/private/buyBombs
content-type: application/json

{
  "bombName":"Mk-III",
  "quantity":10
}

###

###Buy Defense Points

POST http://localhost:5000/private/buyDefensePoints
content-type: application/json

{
  "numOfPoints":100
}

###Create Alliance
POST http://localhost:5000/private/createAlliance
content-type: application/json

{
  "teamName1":"Marauders",
  "teamName2":"Avengers"
}

###Attack
POST http://localhost:5000/private/attack
content-type: application/json

{
  "teamName":"Test team",
  "bombsSelected":[
    {"bombName":"Firecracker","quantity":1},
      {"bombName":"Mk-41","quantity":1}
  ]
}

###
GET http://localhost:5000/update

