GET http://localhost:5000

###

POST http://localhost:5000/create
content-type: application/json

{
  "teamName": "Marasuders",
  "password": "12345678",
  "leader": {
    "name": "Aryan",
    "phone": "8246740057",
    "year": "3rd",
    "branch": "ENC",
    "email": "arysan2563737@gmail.com"
  }
}


###

POST http://localhost:5000/join
content-type: application/json

{
  "code":"RV7vjcaOH",
  "member": {
    "name": "random",
    "phone": "1234567893",
    "year": "3rd",
    "branch": "ENC",
    "email": "test4@test.com"
  }
}