const CountryList: {
  [key: string]: string
} = {
  USA: "POLONIUM",
  CHINA: "POLONIUM",
  JAPAN: "POLONIUM",
  GERMANY: "VLTT",
  INDIA: "VLTT",
  FRANCE: "VLTT",
  ITALY: "LCT",
  BRAZIL: "LCT",
  CANADA: "LCT",
  "SOUTH KOREA": "LITHIUM 6",
  RUSSIA: "LITHIUM 6",
  SPAIN: "LITHIUM 6",
  AUSTRALIA: "LITHIUM 7",
  MEXICO: "LITHIUM 7",
  INDONESIA: "LITHIUM 7",
  TURKEY: "URANIUM 238",
  "SAUDI ARABIA": "URANIUM 238",
  SWITZERLAND: "URANIUM 238",
  POLAND: "URANIUM 235",
  TAIWAN: "URANIUM 235",
  UK: "URANIUM 235",
  AUSTRIA: "LEAD",
  GREECE: "LEAD",
  "HONG KONG": "LEAD",
  UKRAINE: "TUNGSTEN",
  MALAYSIA: "TUNGSTEN",
  THAILAND: "TUNGSTEN",
  NETHERLANDS: "RDJK",
  SINGAPORE: "RDJK",
  ROMANIA: "RDJK",
  DENMARK: "PLUTONIUM 239",
  ARGENTINA: "PLUTONIUM 239",
  NORWAY: "PLUTONIUM 239",
  SWEDEN: "PLUTONIUM 244",
  FINLAND: "PLUTONIUM 244",
}

const team = "USA"

CountryList[team]

export default CountryList
